#! /bin/dash

dte(){
	dte="$(date +"%d.%m.%Y (%a) %I:%M%p")"
	echo "$dte"
}

bat(){
	bat="$(cat /sys/class/power_supply/BAT0/capacity)"
	echo "$bat"
}

###LOOP###

while true; do
	xsetroot -name "$(bat)% Battery | $(dte)"
	sleep 60
done &
